version: "3.9"

services:
  app:
    build:
      context: ./php-code
      dockerfile: Dockerfile
    container_name: php-code-container
    volumes:
      - ./php-code:/var/www/html
    depends_on:
      - db
    expose:
      - 9000 # Expose uniquement en interne pour nginx

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./php-code:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8081:80"

  db:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: appdaff
      POSTGRES_PASSWORD: appdaff
      POSTGRES_DB: appdaff_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db_data:
