services:
  - type: web
    name: appdaf-api
    env: docker
    plan: free
    repo: https://github.com/thetaf313/docker-project.git
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromService:
          type: pserv
          name: appdaf-db
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: appdaf_db
      - key: DB_USER
        value: appdaff
      - key: DB_PASS
        value: appdaff
